### ISSUE TITLE
Best way to handle fallback

### ISSUE THREAD

**Issue by fred** [kenn/standby#29]
In your opinion, what would be the best way to handle fallback to primary in case the replicas are down? 
Let's say the replica is restarted or not available, or just when ActiveRecord cant connect or a timeout occurs. Similar to `Standby.disabled = true` but coming from a rescue block.

**Comment by kenn** [comment]
My answer would be "it depends". If you have a lot of extra capacity on primary, it would make sense to rescue and run the query on primary automatically, but it comes at the cost of potential overload when something bad happens.
